name: Docker

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish-dockerhub:
    if: ${{ github.repository == 'koishijs/boilerplate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Hub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login \
            --username "${DOCKER_USERNAME}" \
            --password-stdin
      - name: Run buildx and push
        env:
          DOCKER_REPO: koishijs/koishi
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKER_REPO}:${GITHUB_REF#refs/tags/} \
            --tag ${DOCKER_REPO}:latest \
            --file ./docker/Dockerfile \
            ./docker
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKER_REPO}:${GITHUB_REF#refs/tags/}-puppeteer \
            --tag ${DOCKER_REPO}:latest-puppeteer \
            --file ./docker/Dockerfile.puppeteer \
            ./docker
      - name: Docker Hub logout
        if: always()
        run: docker logout
